### ISSUE TITLE
White colored text is not visible on white background in light theme

### ISSUE THREAD

**Issue by 0xcrypto** [b2a3e8/jekyll-theme-console#10]
![Screenshot_2019-11-02_06-28-45](https://user-images.githubusercontent.com/6683856/68071690-0d9f8780-fd3a-11e9-9642-4613b6ea52e8.png)

**Comment by b2a3e8** [comment]
I see, maybe a good time to redo the code/syntax colors..
I’ll do that asap.

**Comment by 0xcrypto** [comment]
As a quick hack, add the following in ```_sass/light.scss```
```scss
.highlighter-rouge,
.highlight {
	background: #eee;
	color: #000;
}
```
