### ISSUE TITLE
Undefined variable: "$base-font-weight". on line 17 on gitlab pages

### ISSUE THREAD

**Issue by victor-ide** [b2a3e8/jekyll-theme-console#12]
Hello, I'm facing this issue when configuring the template using the gitlab pages:
```
Configuration file: /builds/id3s3c/id3s3c.gitlab.io/_config.yml
85             Source: /builds/id3s3c/id3s3c.gitlab.io
86        Destination: public
87  Incremental build: disabled. Enable with --incremental
88       Generating... 
89   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main-dark.scss':
90                     Undefined variable: "$base-font-weight". on line 17
91 jekyll 3.8.0 | Error:  Undefined variable: "$base-font-weight". on line 17
92 ERROR: Job failed: exit code 1
```
my _confg.yml file:
```
# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://id3s3c.gitlab.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["README.md"]
theme: jekyll-theme-console
```
Gemfile:
```
source "https://rubygems.org"
ruby RUBY_VERSION

# This will help ensure the proper Jekyll version is running.
# gem "jekyll", "3.4.0"
gem "jekyll", "3.8"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "jekyll-theme-console"
```
.gitlab-ci.yml:
```
image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
```
